---
title: 'Informazioni per la tesi di laurea'
lang: it
---

Sebbene talvolta vi sia una certa sovrapposizione, di norma [la didattica]{.blue}, soprattutto quella "di base", [non riflette gli interessi di ricerca]{.blue} di un docente. 

Le tematiche di cui mi occupo sono: [applicazioni]{.orange} e [metodi]{.orange} di [statistica bayesiana]{.blue} (nonparametrica) & [statistica computazionale]{.blue}. Per maggiori informazioni, si consiglia di consultare la lista delle [pubblicazioni](papers.html), oppure la lista di tesi passate che trovate in questa pagina.

Nel caso di tesi triennali, ho talvolta seguito anche progetti di carattere più [applicativo]{.orange} (ad es. progetti legati ad uno stage esterno), oppure di [statistica metodologica classica]{.blue} (test d'ipotesi, metodi bootstrap, etc.).

Per informazioni riguardanti la tesi, si prega di scrivere una mail a tommaso.rigon\@unimib.it e venire quindi a ricevimento [martedì alle ore 17.30]{.blue}.

## Intelligenza artificiale e LLM {.central}

L'uso di modelli linguistici di grandi dimensioni (ChatGPT, Claude, Gemini, etc.) è [permesso]{.blue} come strumento di supporto: revisione linguistica, controllo di errori, chiarimenti su concetti, debugging del codice. Non è invece ammesso [delegare la produzione dei contenuti]{.orange}: la struttura del lavoro, le scelte metodologiche, le analisi e l'interpretazione dei risultati devono essere opera del candidato.

::: {.column-margin}
Indicazioni in linea con le [raccomandazioni sull'uso dell'IA generativa negli elaborati studenteschi](files/raccomandazioni_IA_unimib.pdf), approvate dal [PQA -- Ramo Didattica]{.blue} dell'Ateneo l'11 aprile 2024.
:::

Resta in capo al candidato [la responsabilità piena di ogni frase e di ogni risultato]{.blue} contenuti nell'elaborato, comprese eventuali imprecisioni, dimostrazioni errate o riferimenti bibliografici inesistenti prodotti dal modello.



[Importante]{.orange}. A partire dall'A.A. 2026/2027, è [obbligatorio dichiarare]{.orange} nelle pagine iniziali della tesi se si è fatto uso o meno di strumenti di intelligenza artificiale, quali e in che misura.

Per le tesi triennali di cui io sarò relatore sarà inoltre prevista una [prova orale]{.blue}, necessaria per valutare l'effettiva conoscenza degli argomenti inclusi nella tesi. Per le tesi magistrali la discussione finale è già prevista dal regolamento del corso di laurea.

## Il software LaTeX {.central}

L'utilizzo del [software LaTeX](https://www.tug.org/texlive/) per la scrittura della tesi è [caldamente raccomandato]{.blue}.

LaTeX può essere scaricato gratuitamente da internet. In alternativa, è possibile usare [Overleaf](https://www.overleaf.com). Per una [guida in italiano]{.blue} all'uso di LaTeX si consiglia [LaTeX per l'impaziente](http://www.lorenzopantieri.net/LaTeX_files/LaTeXimpaziente.pdf) oppure [l'Arte di scrivere con LaTeX](http://www.lorenzopantieri.net/LaTeX_files/ArteLaTeX.pdf).

Viene inoltre reso disponibile un [template LaTeX](files/template_tesi.zip). Se compilato, il risultato finale dovrebbe coincidere con [questo file](files/tesi.pdf), in formato .pdf.

<!-- Si suggeriscono inoltre le seguenti [linee guida per la scrittura di testi matematici](http://www-math.mit.edu/~poonen/papers/writing.pdf). -->


## Studenti e tesi passate {.central}

Vengono riportati nel seguito alcuni degli studenti che ho seguito come relatore o correlatore negli anni passati, insieme al loro percorso successivo, quando noto. Non è una lista esaustiva.

::: {.small-table}

| A.A. | Laurea | Candidata/o | Materiale | Tesi all'estero | *Placement* |
|:-------------:|:-------------:|:--------------|:--------------|:--------------|:--------------|
|  |  | **Laurea Triennale** |  |  |  |
| 2021/2022 | [Triennale]{.blue} | [Anna Petranzan](https://sites.google.com/campus.unimib.it/anna-petranzan/) | [Tesi](files/papers/Petranzan_triennale_858541.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2021/2022 | [Triennale]{.blue} | Marco Carrettoni | [Tesi](files/papers/Carrettoni_triennale_851292.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2021/2022 | [Triennale]{.blue} | Erica Delvino | [Tesi](files/papers/Delvino_triennale_851269.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2021/2022 | [Triennale]{.blue} | [Alessandro Colello](https://stat.utexas.edu/directory/alessandro-colello) |   |  | M.Sc. CLAMSES (Unimib) |
| 2022/2023 | [Triennale]{.blue} | Giulia De Innocentiis | [Tesi](files/papers/DeInnocentiis_triennale_865084.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2022/2023 | [Triennale]{.blue} | Tommaso Menghini | [Tesi](files/papers/Menghini_triennale_864946.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2022/2023 | [Triennale]{.blue} | Marco Nobili |   |  | M.Sc. CLAMSES (Unimib) |
| 2023/2024 | [Triennale]{.blue} | Stefano Andreoli | [Tesi](files/papers/Andreoli_triennale_880053.pdf) |  | M.Sc. CLAMSES (Unimib) |
| 2023/2024 | [Triennale]{.blue} | Riccardo Cicuttin | [Tesi](files/papers/Cicuttin_triennale_879735.pdf) |  | M.Sc. in Mathematical Engineering (Polimi) |
| 2024/2025 | [Triennale]{.blue} | Anna Ciapparelli |   |  | M.Sc. DSBA (Bocconi) |
| 2024/2025 | [Triennale]{.blue} | Federico Boiocchi | [Tesi](files/papers/Boiocchi_triennale_895221.pdf) |  | M.Sc. DSBA (Bocconi) |
| 2024/2025 | [Triennale]{.blue} | Giulio Maria Parisi |   |  | M.Sc. CLAMSES (Unimib) |
| 2024/2025 | [Triennale]{.blue} | Giovanni Pomati |   |  | M.Sc. in Statistics (EPFL) |
| 2025/2026 | [Triennale]{.blue} | Enrico Maria Pedol |   |  | M.Sc. in Statistics and Data Science (LMU Munich) |
| 2025/2026 | [Triennale]{.blue} | Antonio Urso |   |  | M.Sc. CLAMSES (Unimib) |
| 2025/2026 | [Triennale]{.blue} | Giacomo Arrigoni |   |  | M.Sc. CLAMSES (Unimib) |
| 2025/2026 | [Triennale]{.blue} | Francesco Badolato |   |  | M.Sc. CLAMSES (Unimib) |
|  |  | **Laurea Magistrale** |  |  |  |
| 2020/2021 | [Magistrale]{.orange} | [Davide Agnoletto](https://davideagno.github.io) | [Tesi](files/papers/Agnoletto_magistrale.pdf) |  | Ph.D. in Statistics (Unipd) |
| 2022/2023 | [Magistrale]{.orange} | Gabriele Tinè | [Tesi](files/papers/Tine_magistrale_826904.pdf) |  | Data Scientist (IRCCS Istituto Nazionale dei Tumori) |
| 2022/2023 | [Magistrale]{.orange} | Christian Arlenghi |   | Oxford, UK (prof. [Francesco Rampazzo](https://francescorampazzo.com)) | Data Analyst (Deloitte) |
| 2023/2024 | [Magistrale]{.orange} | [Anna Petranzan](https://sites.google.com/campus.unimib.it/anna-petranzan/) | [Tesi](files/papers/Petranzan_magistrale_858541.pdf) |  | Ph.D. in Economics, Statistics and Data Science (Unimib) |
| 2023/2024 | [Magistrale]{.orange} | Luna Cantaroni | [Tesi](files/papers/Cantaroni_magistrale.pdf) |  | Data Scientist (PwC) |
| 2023/2024 | [Magistrale]{.orange} | Marco Carrettoni |   |  | Credit Risk Consultant (KPMG) |
| 2024/2025 | [Magistrale]{.orange} | Francesco Bosco |   |  | Credit Risk Consultant (KPMG) |
| 2024/2025 | [Magistrale]{.orange} | [Alessandro Colello](https://stat.utexas.edu/directory/alessandro-colello) | [Tesi](files/papers/Colello_magistrale.pdf) |  | Ph.D. in Statistics (UT Austin) |
| 2024/2025 | [Magistrale]{.orange} | Maria Regina Mucilli | [Tesi](files/papers/Mucilli_magistrale_872352.pdf) - [Slides](files/papers/Mucilli_magistrale_slides.pdf) |  | Ph.D. in Economics, Statistics and Data Science (Unimib) |
| 2024/2025 | [Magistrale]{.orange} | Tommaso Menghini | [Tesi](files/papers/Menghini_magistrale.pdf) - [Slides](files/papers/Menghini_magistrale_slides.pdf) |  | Statistician (Sigma Consulting) |
| 2024/2025 | [Magistrale]{.orange} | Gaia Addis |   |  | Data Scientist (Cosmo) |
| 2024/2025 | [Magistrale]{.orange} | Lidia Dell'Elba |   | NUS, Singapore (prof.ssa [Maria De Iorio](https://discovery.nus.edu.sg/13583-maria-de-iorio)) |   |
| 2024/2025 | [Magistrale]{.orange} | Antonio Furfaro Serranò |   |  |   |
| 2024/2025 | [Magistrale]{.orange} | Lucrezia Tusetti |   |  | Data Engineer (KPMG) |
| 2025/2026 | [Magistrale]{.orange} | Stefano Andreoli |   |  | Ph.D. in Statistics (Duke) |
|  |  | **Dottorato di Ricerca** |  |  |  |
| 2023 | [**Ph.D.**]{.darkred} (Duke) | [Alessandro Zito](https://alessandrozito.github.io/web/) | [Tesi](https://alessandrozito.github.io/web/files/thesis_alezito.pdf) - [Slides](https://alessandrozito.github.io/web/files/defense_alezito.pdf) |  | Postdoctoral researcher (Harvard) |
| 2024 | [**Ph.D.**]{.darkred} | [Davide Agnoletto](https://davideagno.github.io) | [Tesi](https://www.research.unipd.it/retrieve/2d452b9b-ee95-4a6a-b0d5-9da3429643b4/Tesi_Agnoletto.pdf) |  | Postdoctoral researcher (Duke) |

: {tbl-colwidths="[8, 11, 18, 12, 27, 24]"}

:::

<!-- ## FAQ {.central} -->

<!-- 1.  [Devo ancora finire gli esami, posso cominciare a lavorare alla tesi?]{.blue} Sì, anzi è caldamente raccomandato chiedere informazioni prima del superamento di tutti gli esami. Tuttavia, la scrittura della tesi di laurea è un lavoro a tempo pieno che necessita di [almeno un paio di mesi]{.blue} per una tesi triennale e anche più tempo per una tesi magistrale. Ovviamente, non è possibile laurearsi senza aver superato tutti gli esami. Pertanto, si consiglia di concluderli prima di cominciare a lavorare alla tesi. -->

<!-- 2.  [È possibile proporre un personale progetto per la tesi?]{.blue} Sì, ma verranno considerati solamente progetti estremamente innovativi e che siano [in linea con gli interessi di ricerca]{.orange} del docente. Si raccomanda caldamente di concordare un progetto con il docente prima di cominciare a lavorare. -->

<!-- 3.  [Non ho mai usato LaTeX, posso usare Word?]{.blue} Sì, anche se l'uso del software Microsoft Word / Open Office rimane fortemente sconsigliato per la stesura di documenti scientifici. -->

<!-- 4.  [È possibile scrivere la tesi in lingua inglese?]{.blue} Sì, la tesi di laurea può essere scritta sia in lingua italiana che inglese, a seconda della personale preferenza del candidato. La lingua inglese è caldamente raccomandata per le tesi di ricerca. -->

<!-- 5.  [È possibile provare a pubblicare la propria tesi su una rivista scientifica?]{.blue} Sì, ma solamente se la qualità della tesi (magistrale) è di qualità eccezionale ed estremamente innovativa. Dato che questo implica uno sforzo considerevole ed i tempi delle pubblicazioni scientifiche sono molto lunghi (a volte anche anni), si consiglia questo percorso solamente nel caso in cui il candidato abbia intenzione di proseguire con un dottorato. -->
