---
title: "Project presentation"
subtitle: "Politecnico di Milano - Mathematical Engineering - Bayesian Statistics"
description: "Presentation of a project for the course Bayesian Statistics at the Politecnico di Milano"
date: "2025-09-26"
lang: en
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
page-layout: full
bibliography: biblio.bib
citeproc: true
csl: https://www.zotero.org/styles/journal-of-the-american-statistical-association
reference-location: margin
execute:
  cache: false
format:
  html:
    toc: true
  revealjs:
    output-file: Polimi2025_slides.html
format-links: true
---


## Short Bio

- My name is [Tommaso Rigon]{.blue} and I am a [Senior Assistant Professor]{.orange} (RTD-B).

- [University of Milano-Bicocca]{.blue}, Department of Economics, Management and Statistics (DEMS), Milan, Italy.
  - Senior Assistant Professor (RTD-B), 2023 - Present
  - Junior Assistant Professor (RTD-A), 2020 - 2023

- [Duke University]{.blue}, Department of Statistical Science, Durham (NC), U.S.A.
  - Postdoctoral Associate, 2020 - 2020
  - Research Associate, 2019 - 2020

:::callout-note
#### Education

- [Ph.D. in Statistical Sciences]{.orange}, [Bocconi University](https://www.unibocconi.eu/), Milan, Italy.
- [M.Sc. in Statistical Sciences]{.blue}, [University of Padova](https://www.unipd.it), Padua, Italy.
- [B.Sc. in Statistics, Economics & Finance]{.grey}, [University of Padova](https://www.unipd.it), Padua, Italy.
:::


## Hyperbolic secant regression


:::callout-tip
#### Background

Let $Y_1,\dots,Y_n$ be independent random variable distributed according to a [hyperbolic secant distribution]{.orange}, whose [density]{.blue} is
$$
f(y_i; \theta_i) = \frac{\exp\{\theta_i y_i - \log{\cos(\theta_i)} \}}{2 \cosh(\pi y_i / 2)}, \qquad y_i \in \mathbb{R}, \; \theta_i \in \left(-\frac{\pi}{2}, \frac{\pi}{2}\right).
$$
This distribution is discussed in @Morris1982 and is an instance of highly tractable [exponential family]{.orange} having a [quadratic variance]{.blue} function. 
:::


- This distribution can be employed to build a novel [generalized linear model]{.blue} (GLM), which automatically incorporates [heteroskedasticity]{.orange} and exhibits [heavier tails]{.blue} than the Gaussian law.

- There are multiple application areas for such a regression technique, including (but not limited to) financial data.

## Objectives and expectations

:::callout-tip
#### Research gap
- A systematic [Bayesian investigation]{.orange} of such a GLM is entirely lacking. In principle, this GLM framework can be combined with modern Bayesian tools for regression, such as:
  - Variable selection and regularization, e.g., shrinkage priors or spike-and-slab priors.
  - Random effects (parametric and nonparametric).
  - Generalized Additive Models (GAMs), e.g., Gaussian Processes.

- [Overdispersion]{.orange} may require novel generalized Bayes techniques [@Agnoletto2025].

- A [Polya-gamma]{.blue} data augmentation scheme may be applicable by adapting the results in @Polson2013. If not, Hamiltonian Monte Carlo (HMC) remains a feasible option.

:::

:::callout-warning
#### Expected outcome

The group is expected to implement and develop 2–3 of the research gaps outlined above.  

I expect the group to be proficient in R programming (knowledge of C++ is a strong asset, though probably not essential). Most of the work will focus on the practical implementation of these ideas.
:::


## References
